### ISSUE TITLE
keys and excludes are not working

### ISSUE THREAD

**Issue by kekepins** [RoyaleAPI/cr-api#414] opened 2018-07-27 07:44 UTC
### Idea/request:
  1. Briefly explain the idea or request.
Request with excludes or keys has no effect on the result
  1. Briefly explain the rationale behind the request, or provide a use case.
Executing:
https://api.royaleapi.com/player/UJRJRCY9?keys=name,tag
https://api.royaleapi.com/player/UJRJRCY9?exclude=arena
  1. In which request/endpoint does this apply?
Tested only with player
  1. Use the boxes at the bottom of this template to demonstrate a request and expected response.

### Issue Report:
  1. Did you encounter this recently, or has this bug always been there?
Just started to us use the api this week
  1. Expected behaviour: 
  1. Console logs (if applicable): 
  1. Screenshots (if applicable):

### Request Details:

```
GET
https://api.royaleapi.com/player/UJRJRCY9?exclude=arena

```

### Response Details:

```
Code: 200
{"tag":"UJRJRCY9","name":"?houlala?","trophies":4380,"rank":null,"arena":{"name":"Challenger II","arena":"Le
```

**Comment by fourjr** [comment] 2018-07-27 11:59
Duplicate of #395

**Closed by fourjr** 2018-07-27 11:59 UTC
