### ISSUE TITLE
Tournaments data outdated and inefficient pagination

### ISSUE THREAD

**Issue by gogaz** [RoyaleAPI/cr-api#430] opened 2018-09-21 00:22 UTC
### Issue Report:
  1. Did you encounter this recently, or has this bug always been there?
I started working with tournaments yestarday. Pagination didn't seem to work but tournaments data looked up to date
  1. Encountered behaviour: 
`/tournaments/joinable`, `/tournaments/open` and `/tournaments/1k` both return the exact same data which is outdated regardless of the `page` argument.

Below `createTime` indicates 20 September 08:21:34 UTC and `updatedAt` refers to 08:22:58 UTC

### Request Details:

```
GET
https://api.royaleapi.com/tournaments/open
https://api.royaleapi.com/tournaments/open?page=10
```

### Response Details:

```
Code: 200
[
    {
        "tag": "URQ0CL9",
        "name": "iran2",
        "open": true,
        "maxPlayers": 1000,
        "currentPlayers": 1,
        "status": "inPreparation",
        "createTime": 1537431694,
        "prepTime": 7200,
        "startTime": null,
        "endTime": null,
        "duration": 3600,
        "description": "",
        "updatedAt": 1537431778,
        "members": []
    },
...
]

Code: 200
[
    {
        "tag": "URQ0CL9",
        "name": "iran2",
        "open": true,
        "maxPlayers": 1000,
        "currentPlayers": 1,
        "status": "inPreparation",
        "createTime": 1537431694,
        "prepTime": 7200,
        "startTime": null,
        "endTime": null,
        "duration": 3600,
        "description": "",
        "updatedAt": 1537431778,
        "members": []
    },
...
]
```

**Comment by gogaz** [comment] 2018-09-22 12:27
The data seems fresh now but the pagination is still not working

**Comment by fourjr** [comment] 2018-09-27 15:34
Duplicate of #407

**Closed by fourjr** 2018-09-27 15:34 UTC
Labels: duplicate
